# Generated by Django 4.1.4 on 2022-12-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/banner_img')),
                ('discount_deal', models.CharField(max_length=100)),
                ('quote', models.CharField(blank=True, max_length=100, null=True)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
