# Generated by Django 4.1.4 on 2022-12-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
